import gql from 'graphql-tag'
import { Component } from 'react'
import { graphql } from 'react-apollo'

class AuthComponent extends Component {
  triggerMutation = () => {
    const { email, password, onAuth } = this.props
    return onAuth(email, password)
  }

  render() {
    const { children } = this.props

    // Here we pass the function to trigger the mutation to the children of the component
    return children && children(this.triggerMutation)
  }
}

const AUTH_MUTATION = gql`
  mutation auth(
    $email: String!,
    $password: String!
  ) {
    auth(email: $email, password: $password) @client
  }
`

const mutationResultToAuth = () =>
  result => {
    if (result.errors || !result.data) {
      throw new Error("Failed to mutate")
    }

    return result.data.auth
  }

// This maps the mutation function generated by graphql
// to make it accessible in the components props
const mapMutationToProps = ({mutate}) => ({
  onAuth: (email, password) => {
    return mutate({
      variables: { email, password }
    })
    .then(mutationResultToAuth())
  }
})

export const AuthMutation  = graphql(AUTH_MUTATION, {
  props: mapMutationToProps,
})(AuthComponent)
